## Crontab changes only
-w /var/spool/cron -p wa -k cron_changes
-w /var/spool/cron/crontabs -p wa -k cron_changes

## User account changes
-w /etc/passwd -p wa -k user_changes
-w /etc/group -p wa -k user_changes
