#!/bin/bash
ALERT_FILE=$1
WEBHOOK_URL="http://localhost:5001/wazuh-alert"
curl -s -X POST "$WEBHOOK_URL" \
  -H "Content-Type: application/json" \
  -d @"$ALERT_FILE" \
  --connect-timeout 30 \
  --max-time 60
exit 0
